data_dir: .
exclude:
  - README.md
  - CHANGELOG.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - package.json
  - icons-manifest.json
  - bin
  - sandbox
  - stash

# Google Analytics Tracking ID
google_analytics: UA-63028889-4